import { Venue } from '@/shared/types';

// Seed venues with v3.0 fields — all owned by 'system', pre-approved
type SeedVenue = Omit<Venue, 'createdAt'>;

const SEED_DEFAULTS: Pick<Venue, 'ownerId' | 'source' | 'approvalStatus'> = {
  ownerId: 'system',
  source: 'seed',
  approvalStatus: 'approved',
};

const RAW_LUCKNOW_VENUES = [

  // ── BADMINTON ───────────────────────────────────────────────────────────────
  {
    id: 'courtitude-gomti',
    name: 'Courtitude Badminton Academy',
    sport: 'badminton',
    area: 'Gomti Nagar',
    address: 'Viram Khand 3, Gomti Nagar, Lucknow',
    coordinates: { lat: 26.8467, lng: 80.9462 },
    price: 250,
    rating: 4.8,
    reviewCount: 134,
    amenities: ['AC', 'Changing Room', 'Parking', 'Coaching', 'Equipment Rental'],
    skillLevel: 'all',
    timings: { open: '05:30', close: '22:00' },
    description: 'Premium air-conditioned badminton courts with professional coaching. Perfect for beginners and pros alike.',
    imageUrl: 'https://images.unsplash.com/photo-1599474924187-334a4ae5ea3c?w=800',
    category: 'Premium Court',
    peakPricing: { morning: 250, afternoon: 200, evening: 350 },
    available: true,
  },
  {
    id: 'smash-arena-indira',
    name: 'Smash Arena',
    sport: 'badminton',
    area: 'Indira Nagar',
    address: 'Sector 14, Indira Nagar, Lucknow',
    coordinates: { lat: 26.8829, lng: 80.9860 },
    price: 180,
    rating: 4.5,
    reviewCount: 89,
    amenities: ['Parking', 'Changing Room', 'Drinking Water'],
    skillLevel: 'beginner',
    timings: { open: '06:00', close: '21:00' },
    description: 'Affordable and beginner-friendly badminton courts in Indira Nagar. Great for casual games.',
    imageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800',
    category: 'Budget Court',
    peakPricing: { morning: 180, afternoon: 150, evening: 220 },
    available: true,
  },
  {
    id: 'primeplay-aliganj',
    name: 'PrimePlay Sports Hub',
    sport: 'badminton',
    area: 'Aliganj',
    address: 'Near Aliganj Market, Lucknow',
    coordinates: { lat: 26.8727, lng: 80.9498 },
    price: 300,
    rating: 4.6,
    reviewCount: 201,
    amenities: ['AC', 'Coaching', 'Cafeteria', 'Parking', 'Equipment Rental', 'Changing Room'],
    skillLevel: 'all',
    timings: { open: '05:00', close: '23:00' },
    description: 'Full-service sports hub in Aliganj with multiple badminton courts, coaching, and cafeteria.',
    imageUrl: 'https://images.unsplash.com/photo-1525921429624-479b6a26d84d?w=800',
    category: 'Sports Hub',
    peakPricing: { morning: 300, afternoon: 240, evening: 400 },
    available: true,
  },
  {
    id: 'shuttle-point-hazratganj',
    name: 'Shuttle Point',
    sport: 'badminton',
    area: 'Hazratganj',
    address: 'Hazratganj Commercial Area, Lucknow',
    coordinates: { lat: 26.8522, lng: 80.9428 },
    price: 220,
    rating: 4.3,
    reviewCount: 67,
    amenities: ['Parking', 'Changing Room'],
    skillLevel: 'intermediate',
    timings: { open: '06:00', close: '21:00' },
    description: 'Centrally located badminton courts in the heart of Hazratganj. Easy access from all areas.',
    imageUrl: 'https://images.unsplash.com/photo-1599474924187-334a4ae5ea3c?w=800',
    category: 'Central Court',
    peakPricing: { morning: 220, afternoon: 180, evening: 280 },
    available: false,
  },
  {
    id: 'ace-badminton-ashiyana',
    name: 'Ace Badminton Club',
    sport: 'badminton',
    area: 'Ashiyana',
    address: 'Ashiyana Colony, Lucknow',
    coordinates: { lat: 26.7934, lng: 80.9082 },
    price: 160,
    rating: 4.2,
    reviewCount: 45,
    amenities: ['Parking', 'Drinking Water'],
    skillLevel: 'beginner',
    timings: { open: '06:00', close: '20:00' },
    description: 'Budget-friendly badminton facility in Ashiyana. Best option for beginners starting their journey.',
    imageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800',
    category: 'Budget Court',
    peakPricing: { morning: 160, afternoon: 130, evening: 200 },
    available: true,
  },

  // ── FOOTBALL ────────────────────────────────────────────────────────────────
  {
    id: 'kickoff-turf-gomti-ext',
    name: 'KickOff Premium Turf',
    sport: 'football',
    area: 'Gomti Nagar Extension',
    address: 'Sushant Golf City Road, Gomti Nagar Extension, Lucknow',
    coordinates: { lat: 26.8109, lng: 81.0034 },
    price: 800,
    rating: 4.9,
    reviewCount: 312,
    amenities: ['Floodlights', 'Changing Room', 'Parking', 'Drinking Water', 'First Aid'],
    skillLevel: 'all',
    timings: { open: '05:00', close: '23:00' },
    description: 'Premium FIFA-quality synthetic turf with floodlights. Best football experience in Lucknow.',
    imageUrl: 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=800',
    category: 'Premium Turf',
    peakPricing: { morning: 800, afternoon: 650, evening: 1100 },
    available: true,
  },
  {
    id: 'goal-zone-sultanpur',
    name: 'Goal Zone Turf',
    sport: 'football',
    area: 'Sultanpur Road',
    address: 'Sultanpur Road, Near Shaheed Path, Lucknow',
    coordinates: { lat: 26.7898, lng: 81.0341 },
    price: 600,
    rating: 4.6,
    reviewCount: 178,
    amenities: ['Floodlights', 'Parking', 'Changing Room'],
    skillLevel: 'all',
    timings: { open: '06:00', close: '22:00' },
    description: 'Great quality turf on Sultanpur Road. Perfect for evening games with friends.',
    imageUrl: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800',
    category: 'Standard Turf',
    peakPricing: { morning: 600, afternoon: 500, evening: 800 },
    available: true,
  },
  {
    id: 'champions-turf-chowk',
    name: 'Champions Turf',
    sport: 'football',
    area: 'Chowk',
    address: 'Near Hussainabad, Chowk, Lucknow',
    coordinates: { lat: 26.8710, lng: 80.9111 },
    price: 500,
    rating: 4.4,
    reviewCount: 95,
    amenities: ['Floodlights', 'Parking'],
    skillLevel: 'intermediate',
    timings: { open: '06:00', close: '22:00' },
    description: 'Affordable football turf in Old Lucknow. Great community vibes and regular tournaments.',
    imageUrl: 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=800',
    category: 'Community Turf',
    peakPricing: { morning: 500, afternoon: 400, evening: 700 },
    available: true,
  },
  {
    id: 'striker-arena-aishbagh',
    name: 'Striker Arena',
    sport: 'football',
    area: 'Aishbagh',
    address: 'Aishbagh Stadium Road, Lucknow',
    coordinates: { lat: 26.8445, lng: 80.9029 },
    price: 700,
    rating: 4.7,
    reviewCount: 145,
    amenities: ['Floodlights', 'Changing Room', 'Parking', 'Cafeteria'],
    skillLevel: 'all',
    timings: { open: '05:30', close: '23:30' },
    description: 'Professional football arena near Aishbagh Stadium. Evening sessions especially popular.',
    imageUrl: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800',
    category: 'Premium Turf',
    peakPricing: { morning: 700, afternoon: 580, evening: 950 },
    available: true,
  },

  // ── SWIMMING ────────────────────────────────────────────────────────────────
  {
    id: 'aqua-hub-gomti',
    name: 'Aqua Hub Swimming Complex',
    sport: 'swimming',
    area: 'Gomti Nagar',
    address: 'Sector B, Gomti Nagar, Lucknow',
    coordinates: { lat: 26.8502, lng: 80.9521 },
    price: 400,
    rating: 4.7,
    reviewCount: 221,
    amenities: ['Olympic Pool', 'Coaching', 'Changing Room', 'Parking', 'Jacuzzi'],
    skillLevel: 'all',
    timings: { open: '05:00', close: '21:00' },
    description: 'Olympic-size swimming complex with professional coaching. Suitable for all levels.',
    imageUrl: 'https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?w=800',
    category: 'Olympic Pool',
    peakPricing: { morning: 400, afternoon: 320, evening: 500 },
    available: true,
  },
  {
    id: 'splash-hazratganj',
    name: 'Splash Swimming Academy',
    sport: 'swimming',
    area: 'Hazratganj',
    address: 'MG Road, Hazratganj, Lucknow',
    coordinates: { lat: 26.8536, lng: 80.9400 },
    price: 280,
    rating: 4.4,
    reviewCount: 112,
    amenities: ['Coaching', 'Changing Room', 'Drinking Water'],
    skillLevel: 'beginner',
    timings: { open: '06:00', close: '20:00' },
    description: 'Beginner-focused swimming academy in Hazratganj. Affordable rates with certified coaches.',
    imageUrl: 'https://images.unsplash.com/photo-1519315901367-f34ff9154487?w=800',
    category: 'Training Pool',
    peakPricing: { morning: 280, afternoon: 220, evening: 350 },
    available: true,
  },
  {
    id: 'blue-wave-indira',
    name: 'Blue Wave Aquatics',
    sport: 'swimming',
    area: 'Indira Nagar',
    address: 'Near Lekhraj Market, Indira Nagar, Lucknow',
    coordinates: { lat: 26.8870, lng: 80.9920 },
    price: 350,
    rating: 4.5,
    reviewCount: 87,
    amenities: ['Coaching', 'Changing Room', 'Parking', 'Kids Pool'],
    skillLevel: 'beginner',
    timings: { open: '05:30', close: '21:00' },
    description: 'Family-friendly swimming facility with separate kids pool. Excellent coaching for beginners.',
    imageUrl: 'https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?w=800',
    category: 'Family Pool',
    peakPricing: { morning: 350, afternoon: 280, evening: 420 },
    available: true,
  },

  // ── KABADDI / AKHARA ────────────────────────────────────────────────────────
  {
    id: 'hanuman-akhara-chowk',
    name: 'Hanuman Akhara',
    sport: 'kabaddi',
    area: 'Chowk',
    address: 'Chowk Bazaar, Old Lucknow',
    coordinates: { lat: 26.8698, lng: 80.9087 },
    price: 100,
    rating: 4.6,
    reviewCount: 56,
    amenities: ['Traditional Mat', 'Coaching', 'Changing Room'],
    skillLevel: 'all',
    timings: { open: '05:00', close: '09:00' },
    description: 'Historic akhara with authentic kabaddi training. Rich tradition and expert coaches.',
    imageUrl: 'https://images.unsplash.com/photo-1594737625785-a6cbdabd333c?w=800',
    category: 'Traditional Akhara',
    peakPricing: { morning: 100, afternoon: 100, evening: 100 },
    available: true,
  },
  {
    id: 'sports-kabaddi-aishbagh',
    name: 'Aishbagh Kabaddi Ground',
    sport: 'kabaddi',
    area: 'Aishbagh',
    address: 'Aishbagh Sports Complex, Lucknow',
    coordinates: { lat: 26.8421, lng: 80.9012 },
    price: 150,
    rating: 4.5,
    reviewCount: 34,
    amenities: ['Outdoor Ground', 'Coaching', 'Changing Room', 'Parking'],
    skillLevel: 'intermediate',
    timings: { open: '05:30', close: '08:30' },
    description: 'Professional kabaddi ground with evening training sessions. Home to many state-level players.',
    imageUrl: 'https://images.unsplash.com/photo-1594737625785-a6cbdabd333c?w=800',
    category: 'Sports Complex',
    peakPricing: { morning: 150, afternoon: 120, evening: 150 },
    available: true,
  },
  {
    id: 'pro-kabaddi-gomti',
    name: 'Pro Kabaddi Training Center',
    sport: 'kabaddi',
    area: 'Gomti Nagar',
    address: 'Vibhuti Khand, Gomti Nagar, Lucknow',
    coordinates: { lat: 26.8551, lng: 80.9534 },
    price: 200,
    rating: 4.8,
    reviewCount: 78,
    amenities: ['Indoor Turf', 'AC', 'Coaching', 'Video Analysis', 'Changing Room'],
    skillLevel: 'advanced',
    timings: { open: '06:00', close: '22:00' },
    description: 'Modern kabaddi training center with indoor turf and video analysis. Best for competitive players.',
    imageUrl: 'https://images.unsplash.com/photo-1594737625785-a6cbdabd333c?w=800',
    category: 'Training Center',
    peakPricing: { morning: 200, afternoon: 160, evening: 250 },
    available: true,
  },
];

/**
 * @deprecated Use live Firestore query APIs instead.
 * Retained solely as seed data source for backend/firebase/seed.ts.
 */
export const LUCKNOW_VENUES: SeedVenue[] = RAW_LUCKNOW_VENUES.map(venue => ({
  ...venue,
  ...SEED_DEFAULTS,
})) as SeedVenue[];

export const SPORTS_AREAS = [
  'Gomti Nagar',
  'Gomti Nagar Extension',
  'Aliganj',
  'Hazratganj',
  'Indira Nagar',
  'Chowk',
  'Ashiyana',
  'Sultanpur Road',
  'Aishbagh',
];

export const SPORTS_LIST = [
  { value: 'badminton', label: 'Badminton', emoji: '🏸', color: 'from-yellow-500 to-orange-500' },
  { value: 'football', label: 'Football', emoji: '⚽', color: 'from-green-500 to-emerald-600' },
  { value: 'swimming', label: 'Swimming', emoji: '🏊', color: 'from-blue-500 to-cyan-600' },
  { value: 'kabaddi', label: 'Kabaddi', emoji: '🤼', color: 'from-red-500 to-rose-600' },
] as const;
